2025-01-23 19:53:44,926 - ERROR - 未捕获的异常:
Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 450, in closeEvent
    def closeEvent(self, event):
    
KeyboardInterrupt
2025-01-23 21:57:23,865 - ERROR - 未捕获的异常:
Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 450, in closeEvent
    def closeEvent(self, event):
    
KeyboardInterrupt
2025-01-24 20:10:03,387 - ERROR - 未捕获的异常:
Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 451, in closeEvent
    def closeEvent(self, event):
    
KeyboardInterrupt
2025-01-24 20:32:37,011 - ERROR - 未捕获的异常:
Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 451, in closeEvent
    def closeEvent(self, event):
    
KeyboardInterrupt
2025-01-24 20:51:20,799 - ERROR - 未捕获的异常:
Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 451, in closeEvent
    def closeEvent(self, event):
    
KeyboardInterrupt
2025-01-25 21:05:09,794 - ERROR - 未捕获的异常:
Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 451, in closeEvent
    def closeEvent(self, event):
    
KeyboardInterrupt
2025-01-28 17:02:02,056 - ERROR - 未捕获的异常:
Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 495, in closeEvent
    def closeEvent(self, event):
    
KeyboardInterrupt
2025-01-30 16:01:19,507 - ERROR - 初始化错误: 'MainWindow' object has no attribute 'pushButton_3'
2025-01-30 16:01:19,508 - ERROR - Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 199, in __init__
    self.pushButton_3.clicked.connect(self.run_pic_mark)  # 标记目录版面
    ^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'pushButton_3'

2025-01-30 16:01:19,508 - ERROR - 程序启动错误: 'MainWindow' object has no attribute 'pushButton_3'
2025-01-30 16:01:19,508 - ERROR - Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 575, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/Users/shijian/VSCode/autoContents/main.py", line 199, in __init__
    self.pushButton_3.clicked.connect(self.run_pic_mark)  # 标记目录版面
    ^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'pushButton_3'

2025-01-30 16:01:25,889 - ERROR - 初始化错误: 'MainWindow' object has no attribute 'pushButton_3'
2025-01-30 16:01:25,890 - ERROR - Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 199, in __init__
    self.pushButton_3.clicked.connect(self.run_pic_mark)  # 标记目录版面
    ^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'pushButton_3'

2025-01-30 16:01:25,890 - ERROR - 程序启动错误: 'MainWindow' object has no attribute 'pushButton_3'
2025-01-30 16:01:25,890 - ERROR - Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 575, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/Users/shijian/VSCode/autoContents/main.py", line 199, in __init__
    self.pushButton_3.clicked.connect(self.run_pic_mark)  # 标记目录版面
    ^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'pushButton_3'

2025-01-30 16:01:27,322 - ERROR - 初始化错误: 'MainWindow' object has no attribute 'pushButton_3'
2025-01-30 16:01:27,323 - ERROR - Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 199, in __init__
    self.pushButton_3.clicked.connect(self.run_pic_mark)  # 标记目录版面
    ^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'pushButton_3'

2025-01-30 16:01:27,323 - ERROR - 程序启动错误: 'MainWindow' object has no attribute 'pushButton_3'
2025-01-30 16:01:27,323 - ERROR - Traceback (most recent call last):
  File "/Users/shijian/VSCode/autoContents/main.py", line 575, in <module>
    window = MainWindow()
             ^^^^^^^^^^^^
  File "/Users/shijian/VSCode/autoContents/main.py", line 199, in __init__
    self.pushButton_3.clicked.connect(self.run_pic_mark)  # 标记目录版面
    ^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'pushButton_3'

